version: '3' 
services:
  knime-vnc-docker:
    image: openkbs/knime-vnc-docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knime-vnc-docker
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
    #env_file:
    #  - ./.env
    ports:
      - 5901:5901
      - 6901:5601
    volumes:
      - ./workspace:/home/developer/workspace
      - ./.eclipse:/home/developer/.eclipse

